apps/therapy/urls.py
from django.conf.urls import url, include
from apps.therapy import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'therapy'

urlpatterns = [
    url(r'^inicio/$', views.therapy_request, name='home'),
    url(r'^(?P<pk>[0-9]+)/$', views.session_detail, name='therapy-detail'),
    url(r'^crear/$', views.session_create, name='therapy-create'),
    url(r'^(?P<pk>[0-9]+)/editar/$', views.session_update, name='therapy-edit'),
    url(r'^(?P<pk>[0-9]+)/eliminar/$', views.session_delete, name='therapy-delete'),
    url(r'^$', views.log_in, name='log-in'),
    url(r'^log-out/$', views.log_out, name='log-out'),
    url(r'^terapias/$', views.therapy_request, name='therapy-request'),
    url(r'^seguimiento/(?P<pk>\d+)/$', views.therapy_followup, name='therapy-followup'),
    url(r'^perfil/(?P<pk>[0-9]+)/editar/$', views.profile_edit, name='profile-edit'),
    url(r'^comunidad/$', views.therapy_forums, name='therapy-forums'),
    url(r'^comunidad/(?P<pk>[0-9]+)/$', views.thread_detail_view, name='thread-detail'),
    url(r'^comunidad/crear/$', views.thread_create, name='thread-create'),
    url(r'^comunidad/(?P<pk>[0-9]+)/responder/$', views.thread_reply, name='thread-reply'),
    url(r'^comunidad/(?P<pk>[0-9]+)/editar/$', views.thread_update, name='thread-edit'),
    url(r'^comunidad/(?P<pk>[0-9]+)/eliminar/$', views.thread_delete, name='thread-delete'),
    url(r'^recursos/$', views.therapy_resources, name='therapy-resources'),
    url(r'^recursos/crear/$', views.resource_create, name='resource-create'),
    url(r'^recursos/(?P<pk>[0-9]+)/editar/$', views.resource_edit, name='resource-edit'),
    url(r'^recursos/(?P<pk>[0-9]+)/eliminar/$', views.resource_delete, name='resource-delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # registrar urls de nuestra aplicacion therapy
    url(r'^', include('apps.therapy.urls'))
]

# Esto no es adecuado para produccion !! 
# Para mas informacion de como servir estos archivos en: 
# https://docs.djangoproject.com/en/1.11/howto/static-files/deployment/
urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/therapy/models.py
from django.db import models
from django.urls import reverse_lazy
from django.conf import settings

class BaseName(models.Model):
    name = models.CharField(max_length=150, verbose_name='Nombre')
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name

class Profiles(BaseName):
    username = models.CharField(max_length=150, verbose_name='Nombre')
    age = models.IntegerField(verbose_name='Edad')
    therapycount = models.IntegerField(verbose_name='Numero de Terapias')
    wellbeing = models.IntegerField(verbose_name='Bienestar')
    currentmood = models.CharField(max_length=150, verbose_name='Estado de Animo')
    stresslevel = models.IntegerField(verbose_name='Nivel de Estres')
    anxietylevel = models.IntegerField(verbose_name='Nivel de Ansiedad')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario')

    class Meta:
        verbose_name = 'Perfil de Usuario'
        verbose_name_plural = 'Perfiles de Usuarios'

    def get_profile_url(self):
        return reverse_lazy('therapy:therapy-followup', kwargs={'pk': self.pk})
    
    def get_edit_url(self):
        return reverse_lazy('therapy:profile-edit', kwargs={'pk': self.pk})

class Categories(BaseName):
    class Meta:
        verbose_name = 'Categoria de Terapia'
        verbose_name_plural = 'Categorias de Terapias'

class Doctors(BaseName):
    class Meta:
        verbose_name = 'Doctor'
        verbose_name_plural = 'Doctores'

class Sessions(BaseName):
    session_id = models.AutoField(primary_key=True)
    description = models.CharField(max_length=256, verbose_name='Descripcion')
    date_created = models.DateTimeField(auto_now_add=True)
    user_id = models.IntegerField()
    found = models.BooleanField(default=False)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, verbose_name='Categoria')
    doctor = models.ForeignKey(Doctors, on_delete=models.CASCADE, verbose_name='Doctor')
    therapy_date = models.DateField(max_length=256, verbose_name='Fecha de Terapia')
    therapy_time = models.TimeField(auto_now=False, auto_now_add=False, verbose_name='Hora de Terapia')

    class Meta:
        verbose_name = 'Terapia'
        verbose_name_plural = 'Terapias'

    def get_edit_url(self):
        return reverse_lazy('therapy:therapy-edit', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse_lazy('therapy:therapy-delete', kwargs={'pk': self.pk})

    def get_detail_url(self):
        return reverse_lazy('therapy:therapy-detail', kwargs={'pk': self.pk})
    
class Threads(BaseName):
    thread_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150, verbose_name='Titulo')
    initial_post = models.TextField(max_length=1000, verbose_name='Mensaje Inicial')
    date_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario')

    class Meta:
        verbose_name = 'Hilo del Foro'
        verbose_name_plural = 'Hilos del Foro'

    def get_reply_url(self):
        return reverse_lazy('therapy:thread-reply', kwargs={'pk': self.pk})

    def get_edit_url(self):
        return reverse_lazy('therapy:thread-edit', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse_lazy('therapy:thread-delete', kwargs={'pk': self.pk})

    def get_detail_url(self):
        return reverse_lazy('therapy:thread-detail', kwargs={'pk': self.pk})

class Posts(BaseName):
    thread = models.ForeignKey(Threads, on_delete=models.CASCADE, related_name='posts', verbose_name='Hilo')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario')
    message = models.TextField(verbose_name='Mensaje')
    date_posted = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')

    class Meta:
        verbose_name = 'Publicación del Foro'
        verbose_name_plural = 'Publicaciones del Foro'
        ordering = ['date_posted']

class Resources(BaseName):
    title = models.CharField(max_length=150, verbose_name='Titulo')
    text = models.TextField(max_length=1000, verbose_name='Texto')
    icon = models.ImageField(upload_to='therapy', verbose_name='Icono')
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, verbose_name='Categoria')
    date_posted = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuario')

    class Meta:
        verbose_name = 'Recurso'
        verbose_name_plural = 'Recursos'
        ordering = ['date_posted']
    
    def get_edit_url(self):
        return reverse_lazy('therapy:resource-edit', kwargs={'pk': self.pk})
    
    def get_delete_url(self):
        return reverse_lazy('therapy:resource-delete', kwargs={'pk': self.pk})

apps/therapy/forms.py
from django import forms
from .models import Sessions, Threads, Posts, Profiles, Resources


class therapyForm(forms.ModelForm):
    class Meta:
        model = Sessions
        fields = ['description', 'category', 'doctor', 'therapy_date', 'therapy_time']

class NewThreadForm(forms.ModelForm):
    class Meta:
        model = Threads
        fields = ['title', 'initial_post']

class NewPostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['message']
    
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profiles
        fields = ['age', 'currentmood', 'wellbeing', 'stresslevel', 'anxietylevel']

class ResourceForm(forms.ModelForm):
    class Meta:
        model = Resources
        fields = ['title', 'text', 'icon', 'category']

class LoginForm(forms.Form):
    username = forms.CharField(label='Usuario')
    password = forms.CharField(widget=forms.PasswordInput, label="Contraseña")

apps/therapy/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .models import Sessions, Categories, Posts, Threads, Profiles, Resources
from .forms import therapyForm, LoginForm, NewThreadForm, NewPostForm, ProfileForm, ResourceForm


# Create your views here.

def log_in(request):
    form = LoginForm(request.POST or None)
    context = {'message': None, 'form': form}
    if request.POST and form.is_valid():
        user = authenticate(**form.cleaned_data)
        if user is not None:
            if user.is_active:
                login(request, user)

                profile, created = Profiles.objects.get_or_create(
                    user=user,
                    defaults={'username': user.username, 'user_id': user.id, 'age': 0, 'therapycount': 0, 'wellbeing': 0, 'currentmood': '', 'stresslevel': 0, 'anxietylevel': 0}
                )
                
                return redirect('therapy:home')
            else:
                context['message'] = 'El usuario ha sido desactivado'
        else:
            context['message'] = 'Usuario o contraseña incorrecta'
    return render(request, 'therapy/login.html', context)


# decorador para restringir el acceso a solo usuarios autenticados
@login_required
def log_out(request):
    logout(request)
    return redirect('therapy:log-in')


@login_required
def session_list(request):
    therapy = Sessions.objects.all()
    return render(request, 'therapy/index.html', {'therapy': therapy})


@login_required
def session_detail(request, pk):
    try:
        # recuperamos el objeto mediante la
        # API de abstracción de base de datos
        # que ofrece Django
        m = Sessions.objects.get(pk=pk)
    except Sessions.DoesNotExist:
        raise Http404("Esta sesion no está agendada")

    # version con shortcuts de django, equivalente al codigo anterior
    # m = get_object_or_404(therapy, pk=pk)
    return render(request, 'therapy/detail.html', {'session': m})

@login_required
def session_create(request):
    if request.method == 'POST':
        form = therapyForm(request.POST, request.FILES)
        if form.is_valid():
            new_session = form.save(commit=False)
            new_session.user_id = request.user.id
            new_session.name = request.user.username
            new_session.save()
            form.save_m2m()
            return redirect('therapy:home')
    else:
        form = therapyForm()
    return render(request, 'therapy/form.html', {'form': form})


@login_required
def session_update(request, **kwargs):
    # recuperamos el objeto a actualizar
    session = Sessions.objects.get(pk=kwargs.get('pk'))
    # inicializamos el formulario con el objeto recuperado
    form = therapyForm(
        request.POST or None,
        instance=session
    )
    if request.POST and form.is_valid():
        form.save()
        return redirect('therapy:home')
    return render(request, 'therapy/form.html', {'form': form})


@login_required
def session_delete(request, **kwargs):
    session = Sessions.objects.get(pk=kwargs.get('pk'))
    session.delete()
    return redirect('therapy:home')

@login_required
def thread_reply(request, pk):
    thread = get_object_or_404(Threads, pk=pk)
    if request.method == 'POST':
        form = NewPostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.thread = thread  
            post.user = request.user  
            post.save()
            return redirect('therapy:thread-detail', pk=thread.pk)
    else:
        form = NewPostForm()
    return render(request, 'therapy/therapy/thread_reply.html', {'form': form, 'thread': thread})

@login_required
def thread_update(request, pk):
    thread = get_object_or_404(Threads, pk=pk)

    if request.user.id != thread.user_id:
        return HttpResponseForbidden("You are not allowed to edit this thread.")
    if request.method == 'POST':
        form = NewThreadForm(request.POST, request.FILES, instance=thread)
        if form.is_valid():
            form.save()
            return redirect('therapy:thread-detail', pk=thread.pk)  
    else:
        form = NewThreadForm(instance=thread)
    return render(request, 'therapy/therapy/thread_edit.html', {'form': form})

@login_required
def thread_delete(request, **kwargs):
    thread_id = kwargs.get('pk')
    thread = Threads.objects.get(pk=thread_id)

    if request.user.id != thread.user_id:
        return HttpResponseForbidden("You are not allowed to delete this thread.")

    Posts.objects.filter(thread_id=thread_id).delete()

    thread.delete()
    return redirect('therapy:therapy-forums')

@login_required
def therapy_request(request):
    therapies = Sessions.objects.all()
    return render(request, 'therapy/therapy/therapy_request.html', {'therapies': therapies})

@login_required
def therapy_forums(request):
    threads = Threads.objects.all()
    return render(request, 'therapy/therapy/therapy_forums.html', {'threads': threads})

@login_required
def therapy_resources(request):
    resources = Resources.objects.all()
    return render(request, 'therapy/therapy/therapy_resources.html', {'resources': resources})

@login_required
def resource_create(request):
    form = ResourceForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            new_resource = form.save(commit=False)
            new_resource.user_id = request.user.id
            new_resource.save()
            return redirect('therapy:therapy-resources')
    return render(request, 'therapy/therapy/resource_create.html', {'form': form})

@login_required
def resource_edit(request, pk):
    resource = get_object_or_404(Resources, pk=pk)
    if request.user.id != resource.user_id:
        return HttpResponseForbidden("You are not allowed to edit this resource.")
    if request.method == 'POST':
        form = ResourceForm(request.POST, request.FILES, instance=resource)
        if form.is_valid():
            form.save()
            return redirect('therapy:therapy-resources')
    else:
        form = ResourceForm(instance=resource)
    return render(request, 'therapy/therapy/resource_edit.html', {'form': form, 'resource': resource})

@login_required
def resource_delete(request, **kwargs):
    resource_id = kwargs.get('pk')
    resource = Resources.objects.get(pk=resource_id)
    if request.user.id != resource.user_id:
        return HttpResponseForbidden("You are not allowed to delete this resource.")
    resource.delete()
    return redirect('therapy:therapy-resources')

@login_required
def thread_detail_view(request, pk):
    thread = get_object_or_404(Threads, pk=pk)  
    replies = Posts.objects.filter(thread=thread)  
    return render(request, 'therapy/therapy/thread_detail.html', {'thread': thread, 'replies': replies})

@login_required
def thread_create(request):

    form = NewThreadForm(request.POST or None, request.FILES or None)
    
    if request.method == 'POST':

        if form.is_valid():
            new_thread = form.save(commit=False)
            new_thread.user_id = request.user.id
            new_thread.name = request.user.username
            new_thread.save()

            return redirect('therapy:therapy-forums')  

    return render(request, 'therapy/therapy/thread_create.html', {'form': form})

@login_required
def therapy_followup(request, pk):
    profile = get_object_or_404(Profiles, pk=pk)
    return render(request, 'therapy/therapy/therapy_followup.html', {'profile': profile})

# Editar perfil
@login_required
def profile_edit(request, pk):
    profile = get_object_or_404(Profiles, pk=pk)
    if request.user.id != profile.user_id:
        return HttpResponseForbidden("You are not allowed to edit this thread.")
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('therapy:therapy-followup', pk=pk)
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'therapy/therapy/profile_edit.html', {'form': form, 'profile': profile})

apps/therapy/templates/therapy/fragments/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <!--Import Google Icon Font-->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <style>
        .errorlist {
            color: #F44336 !important;
        }
    </style>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <style>

        .brand-logo {
            font-family: 'Roboto Mono', monospace;
            font-weight: 500;
        }
    </style>
</head>
<body>
<nav class="grey darken-2 lighten-1" role="navigation">
    <div class="nav-wrapper container">

        <a id="logo-container" href="{% url 'therapy:home' %}" class="brand-logo deep-orange-text">
            <img
              src="https://i.postimg.cc/3ynFXXvL/image.jpg"
              alt="NeuroHelp Logo"
              style="height: 70px"
            />
          </a>
        {% if request.user.is_authenticated %}
            
        {% endif %}
        {% if request.user.is_authenticated %}
            <ul class="right hide-on-med-and-down">
                <li><a href="{% url 'therapy:therapy-request' %}">Sesion-Online</a></li>
                <li><a href="{% url 'therapy:therapy-resources' %}">Recursos</a></li>
                <li><a href="{% url 'therapy:therapy-forums' %}">Comunidad</a></li>
                <li><a href="{% url 'therapy:therapy-followup' pk=request.user.id %}">Seguimiento</a></li>

                <li><a href="{% url 'therapy:log-out' %}">Salir </a></li>
                <span style="margin-left: 20px;" class="deep-orange-text">Bienvenido '{{ request.user.username }}'</span>
            </ul>
            <ul id="nav-mobile" class="side-nav">
                <li><a href="{% url 'therapy:therapy-request' %}">Sesion-Online</a></li>
                <li><a href="{% url 'therapy:therapy-resources' %}">Recursos</a></li>
                <li><a href="{% url 'therapy:therapy-forums' %}">Comunidad</a></li>
                <li><a href="{% url 'therapy:therapy-followup' pk=request.user.id %}">Seguimiento</a></li>

                <li><a href="{% url 'therapy:log-out' %}">Salir </a></li>
            </ul>
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        {% endif %}
    </div>
</nav>
<div class="container">
    <div class="section">
        {% block main-content %}{% endblock %}
    </div>
    <br><br>
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

<script>
    $(document).ready(function () {
        $('select').material_select();

         $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15, // Creates a dropdown of 15 years to control year,
            today: 'Today',
            clear: 'Clear',
            close: 'Ok',
            closeOnSelect: false // Close upon selecting a date,
          });
    });
</script>

</body>
</html>

apps/therapy/templates/therapy/fragments/forms.html
{% load widget_tweaks %}
<form enctype="multipart/form-data" method="post" >
    {% csrf_token %}
    {% for field in form %}
        <div class="row" >
            {% if field.errors %}
               {{ field.errors }}
            {% endif %}
            <div class="browser-default input-field col s12">
                {% comment %}
                     De esta manera podemos hacer formularios reutilizables con widget_tweaks,
                     tambien podemos añadir librerias a nuestro gusto
                {% endcomment %}
                {% if field|widget_type == 'clearablefileinput' %}
                    <p class="grey-text"> {{ field.label }} </p>
                    {% render_field field class+="validate" %}
                {% else %}
                    {% render_field field class+="validate" %}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% endif %}
            </div>
        </div>
    {% endfor %}

    <div class="row">
        <button class="btn waves-effect waves-light right red darken-1" type="submit" name="action">Entrar
            <i class="material-icons right">send</i>
        </button>
    </div>
</form>

</script>